import { MODULE_NAME } from './constants';

export const SET_PRODUCTS = `${MODULE_NAME}.SET_PRODUCTS`;

export const ADD_TO_CART = `${MODULE_NAME}.ADD_TO_CART`;
export const REMOVE_FROM_CART = `${MODULE_NAME}.REMOVE_FROM_CART`;

export const TOGGLE_FAVORITE = `${MODULE_NAME}.TOGGLE_FAVORITE`;

export const GET_PRODUCTS = `${MODULE_NAME}.GET_PRODUCTS`;
export const GET_PRODUCTS_SUCCESS = `${MODULE_NAME}.GET_PRODUCTS_SUCCESS`;
export const GET_PRODUCTS_FAILURE = `${MODULE_NAME}.GET_PRODUCTS_FAILURE`;
